import { RuleAmendmentRecord } from '../types';

export const KERALA_BUILDING_RULE_AMENDMENTS: RuleAmendmentRecord[] = [
  {
    id: 'amend-2026-02',
    orderNumber: 'GO(P) No. 12/2026/LSGD',
    notificationDate: 'February 15, 2026',
    titleEn: 'Clarification on Small Plot (<125 sq.m) Fire Wall and Boundary Clearances',
    titleMl: '125 ച.മീറ്ററിൽ താഴെയുള്ള ചെറിയ പ്ലോട്ടുകളിലെ ഫയർ വാളും അതിർത്തി അകലവും സംബന്ധിച്ച ഉത്തരവ്',
    affectedRules: ['KMBR Rule 60', 'KPBR Rule 62', 'Table 4'],
    summaryEn: 'Permits construction touching boundary on one side with solid masonry fire wall if neighbor gives registered consent or if side width is <= 0.6m in plots <= 125 sq.m.',
    summaryMl: '125 ചതുരശ്ര മീറ്ററിൽ താഴെയുള്ള പ്ലോട്ടുകളിൽ അയൽവാസിയുടെ രജിസ്റ്റർ ചെയ്ത സമ്മതപത്രത്തോടെയോ അല്ലെങ്കിൽ 0.6 മീറ്റർ അകലത്തിലോ ഫയർ വാളോടെ ഒരു വശം അതിർത്തി ചേർത്ത് നിർമ്മിക്കാൻ അനുമതി നൽകി.',
  },
  {
    id: 'amend-2025-08',
    orderNumber: 'GO(P) No. 04/2025/LSGD',
    notificationDate: 'August 20, 2025',
    titleEn: 'Green Building FAR Bonus & EV Charging Station Provisions in Commercial & Group A1 Apartments',
    titleMl: 'ഗ്രീൻ ബിൽഡിംഗ് FAR ബോണസും വാണിജ്യ/അപ്പാർട്ട്മെന്റ് സമുച്ചയങ്ങളിലെ ഇ.വി ചാർജിംഗ് പോയിന്റുകളും',
    affectedRules: ['KMBR Rule 29', 'KPBR Rule 29', 'Rule 31(Parking)'],
    summaryEn: '5% bonus FAR for GRIHA / IGBC 4-star certified buildings; Mandatory 10% of total car parking slots designated with Level 2 AC EV chargers for commercial and apartment complexes.',
    summaryMl: 'ഗ്രീൻ റേറ്റിംഗ് ഉള്ള കെട്ടിടങ്ങൾക്ക് 5% അധിക FAR ബോണസ്; വാണിജ്യ/പാർപ്പിട സമുച്ചയങ്ങളിൽ ആകെ പാർക്കിംഗിന്റെ 10% ഇലക്ട്രിക് വാഹന ചാർജിംഗ് പോയിന്റുകളാക്കണം.',
  },
  {
    id: 'amend-2024-04',
    orderNumber: 'GO(Ms) No. 89/2024/LSGD',
    notificationDate: 'April 10, 2024',
    titleEn: 'K-Smart Automated Digital Plan Scrutiny & Low-Risk Self Certification Guidelines',
    titleMl: 'കെ-സ്മാർട്ട് ഓൺലൈൻ ഓട്ടോമേറ്റഡ് പ്ലാൻ പരിശോധനയും ലോ-റിസ്ക് സെൽഫ് സർട്ടിഫിക്കേഷനും',
    affectedRules: ['KMBR Rule 5', 'KPBR Rule 5', 'Rule 10(Permit Issuance)'],
    summaryEn: 'Instant building permit issuance through self-certification for residential buildings up to 300 sq.m (low risk category) with strict automated drawing scrutiny standards.',
    summaryMl: '300 ചതുരശ്ര മീറ്റർ വരെയുള്ള ചെറിയ വീടുകൾക്ക് സെൽഫ് സർട്ടിഫിക്കേഷൻ വഴി ഉടനടി കെട്ടിട പെർമിറ്റ് ലഭ്യമാക്കുന്നതിനുള്ള കെ-സ്മാർട്ട് ചട്ടങ്ങൾ.',
  },
  {
    id: 'amend-2023-11',
    orderNumber: 'GO(P) No. 16/2023/LSGD',
    notificationDate: 'November 18, 2023',
    titleEn: 'Rooftop Solar PV Installation Mandate and Purchasable FAR Slabs',
    titleMl: 'റൂഫ്‌ടോപ്പ് സോളാർ പാനൽ നിർബന്ധമാക്കലും അധിക FAR നിരക്ക് പരിഷ്കരണവും',
    affectedRules: ['KMBR Rule 49', 'KPBR Rule 49', 'Rule 29(4)'],
    summaryEn: 'Mandatory on-grid rooftop solar PV for all commercial buildings above 200 sq.m and other occupancies above 500 sq.m. Standardized fee slabs for purchasable FAR.',
    summaryMl: '200 ച.മീറ്ററിന് മുകളിലുള്ള വാണിജ്യ കെട്ടിടങ്ങൾക്കും 500 ച.മീറ്ററിന് മുകളിലുള്ള മറ്റ് കെട്ടിടങ്ങൾക്കും റൂഫ്‌ടോപ്പ് സോളാർ നിർബന്ധമാക്കി.',
  },
  {
    id: 'amend-2020-09',
    orderNumber: 'GO(P) No. 47/2020/LSGD',
    notificationDate: 'September 22, 2020',
    titleEn: 'Kerala Municipality Building (Amendment) Rules, 2020 - Comprehensive Rationalization',
    titleMl: 'കേരള മുനിസിപ്പാലിറ്റി കെട്ടിട നിർമ്മാണ (ഭേദഗതി) ചട്ടങ്ങൾ 2020',
    affectedRules: ['KMBR Rule 22', 'Rule 27', 'Rule 31', 'Rule 47', 'Rule 48'],
    summaryEn: 'Rationalized road width requirements for residential homes up to 300 sq.m; standard 7.5m clearance between open drinking well and septic tank/soak pit reaffirmed.',
    summaryMl: '300 ചതുരശ്ര മീറ്റർ വരെയുള്ള വീടുകൾക്കുള്ള വഴി വീതി ഇളവുകൾ; കുടിവെള്ള കിണറും സെപ്റ്റിക് ടാങ്കും തമ്മിൽ 7.5 മീറ്റർ അകലം കർശനമാക്കി.',
  },
];
