import { AreaStatementData, UploadedDrawing } from '../types';

export interface ProjectPreset {
  id: string;
  nameEn: string;
  nameMl: string;
  categoryEn: string;
  categoryMl: string;
  data: AreaStatementData;
  mockDrawings: UploadedDrawing[];
}

export const SAMPLE_PROJECT_PRESETS: ProjectPreset[] = [
  {
    id: 'preset-panchayat-house',
    nameEn: 'Grama Panchayat 2-Storey Residential House (Group A1)',
    nameMl: 'ഗ്രാമപഞ്ചായത്ത് 2 നില പാർപ്പിട വീട് (Group A1)',
    categoryEn: 'KPBR 2019 · Residential',
    categoryMl: 'കെ.പി.ബി.ആർ 2019 · പാർപ്പിടം',
    data: {
      projectName: 'Green Villa Residential Project',
      applicantName: 'Sanoop Sadanandhan',
      architectEngineerName: 'Er. Rajesh Kumar, B.Tech (Civil), FIE',
      licenseNumber: 'LSGD/ENG/A/2024/0984',
      localBodyName: 'Kizhakkambalam Grama Panchayat',
      wardNumber: 'Ward 08',
      surveyNumber: '142/3-B, Block 12',
      villageName: 'Kizhakkambalam',
      talukName: 'Kunnathunad',
      district: 'Ernakulam',
      jurisdiction: 'KPBR',
      occupancyGroup: 'A1',
      plotType: 'normal',
      plotAreaSqM: 320.0,
      plotAreaCents: 7.9,
      plotWidthM: 16.0,
      plotDepthM: 20.0,
      roadAccessWidthM: 3.8,
      buildingHeightM: 7.2,
      numberOfFloors: 2,
      groundCoverageSqM: 110.0,
      totalBuiltUpAreaSqM: 198.0,
      totalFloorAreaSqM: 182.0,
      totalCarpetAreaSqM: 154.0,
      floors: [
        { floorName: 'Ground Floor', builtUpArea: 110.0, carpetArea: 86.0, occupancy: 'A1', heightFromGround: 0.6 },
        { floorName: 'First Floor', builtUpArea: 88.0, carpetArea: 68.0, occupancy: 'A1', heightFromGround: 3.8 },
      ],
      frontSetbackM: 3.5,
      rearSetbackM: 2.2,
      sideSetback1M: 1.6,
      sideSetback2M: 1.4,
      avgFrontSetbackM: 3.6,
      avgRearSetbackM: 2.3,
      canopyProjectionM: 1.0,
      balconyProjectionM: 0.9,
      carParkingProvided: 1,
      twoWheelerParkingProvided: 2,
      disabledParkingProvided: 0,
      loadingBaysProvided: 0,
      parkingBayWidthM: 2.7,
      parkingBayLengthM: 5.5,
      drivewayWidthM: 3.5,
      openWellInPlot: true,
      distanceWellToSepticTankM: 8.2,
      distanceWellToSoakPitM: 8.5,
      distanceSepticTankToBoundaryM: 1.5,
      rwhTankCapacityLiters: 5000,
      solarPvCapacityKwp: 2.0,
      solidWasteUnitProvided: true,
      biogasPlantOrCompostProvided: true,
      mainStaircaseWidthM: 1.05,
      staircaseTreadCm: 26.0,
      staircaseRiserCm: 16.5,
      staircaseHeadroomM: 2.3,
      minHabitableRoomAreaSqM: 12.5,
      minHabitableRoomWidthM: 3.2,
      minHabitableRoomHeightM: 2.9,
      minKitchenAreaSqM: 8.5,
      minKitchenWidthM: 2.6,
      ventilationRatioPercent: 14.5,
      clearFirePassageWidthM: 3.0,
      hasLift: false,
      hasRampForDisabled: true,
      rampSlopeRatio: 10,
    },
    mockDrawings: [
      { id: 'd-1', category: 'location_plan', name: 'Location_Plan_1to2000.pdf', size: 1420000, status: 'verified', scale: '1:2000', sheetsCount: 1, extractedLabels: ['Key Survey Map', 'North Arrow', 'Ward Boundary'], remarks: 'Clear boundary matching Revenue Sketch', uploadedAt: Date.now() - 3600000 },
      { id: 'd-2', category: 'site_plan', name: 'Site_Plan_Setbacks_Well.dwg', size: 2840000, status: 'verified', scale: '1:200', sheetsCount: 1, extractedLabels: ['Road 3.8m', 'Well to Tank 8.2m', 'Front Yard 3.5m', 'Rear Yard 2.2m'], remarks: 'All boundary clearances checked', uploadedAt: Date.now() - 3400000 },
      { id: 'd-3', category: 'floor_plans', name: 'Ground_and_First_Floor_Plans.pdf', size: 3100000, status: 'verified', scale: '1:100', sheetsCount: 2, extractedLabels: ['Living', 'Dining', '3 Bed Rooms', 'Kitchen 8.5sqm', 'Staircase 1.05m'], remarks: 'Room schedules complete', uploadedAt: Date.now() - 3200000 },
      { id: 'd-4', category: 'elevation_plans', name: 'Front_Side_Elevations.pdf', size: 2150000, status: 'verified', scale: '1:100', sheetsCount: 1, extractedLabels: ['Height 7.2m', 'Parapet 1.0m', 'Plinth +0.6m'], remarks: 'Total height verified', uploadedAt: Date.now() - 3000000 },
      { id: 'd-5', category: 'section_plans', name: 'Cross_Section_Stairs_Toilet.pdf', size: 2450000, status: 'verified', scale: '1:100', sheetsCount: 1, extractedLabels: ['Tread 26cm', 'Riser 16.5cm', 'Headroom 2.3m', 'Floor Height 3.0m'], remarks: 'Structural headroom clear', uploadedAt: Date.now() - 2800000 },
      { id: 'd-6', category: 'service_plans', name: 'Sanitation_SepticTank_SoakPit.pdf', size: 1980000, status: 'verified', scale: '1:100', sheetsCount: 1, extractedLabels: ['Septic Tank Detail', 'Soak Pit Filter Bed', 'Inspection Chamber'], remarks: 'Clear distance from well verified', uploadedAt: Date.now() - 2600000 },
      { id: 'd-7', category: 'rwh_solar_plans', name: 'RWH_5000L_Solar_2kWp_Layout.pdf', size: 1650000, status: 'verified', scale: '1:100', sheetsCount: 1, extractedLabels: ['5000L Masonry Tank', 'Filter Unit', 'Rooftop Solar PV Array'], remarks: 'Complies with Rule 48 & 49', uploadedAt: Date.now() - 2400000 },
    ],
  },
  {
    id: 'preset-municipality-commercial',
    nameEn: 'Municipality 3-Storey Commercial Complex (Group F)',
    nameMl: 'മുനിസിപ്പാലിറ്റി 3 നില വാണിജ്യ സമുച്ചയം (Group F)',
    categoryEn: 'KMBR 2019 · Commercial / Mercantile',
    categoryMl: 'കെ.എം.ബി.ആർ 2019 · വാണിജ്യം',
    data: {
      projectName: 'City Center Commercial Mall',
      applicantName: 'M/s Horizon Ventures LLP',
      architectEngineerName: 'Ar. Ananya Menon, Council of Architecture CA/2018/45120',
      licenseNumber: 'LSGD/ARCH/A/2023/1102',
      localBodyName: 'Kochi Municipal Corporation',
      wardNumber: 'Division 42 (Edappally)',
      surveyNumber: '582/1-A',
      villageName: 'Edappally North',
      talukName: 'Kanayannur',
      district: 'Ernakulam',
      jurisdiction: 'KMBR',
      occupancyGroup: 'F',
      plotType: 'normal',
      plotAreaSqM: 850.0,
      plotAreaCents: 21.0,
      plotWidthM: 24.0,
      plotDepthM: 35.4,
      roadAccessWidthM: 12.0,
      buildingHeightM: 11.5,
      numberOfFloors: 3,
      groundCoverageSqM: 450.0,
      totalBuiltUpAreaSqM: 1250.0,
      totalFloorAreaSqM: 1120.0,
      totalCarpetAreaSqM: 980.0,
      floors: [
        { floorName: 'Ground Floor (Retail)', builtUpArea: 450.0, carpetArea: 360.0, occupancy: 'F', heightFromGround: 0.9 },
        { floorName: 'First Floor (Offices & Shops)', builtUpArea: 420.0, carpetArea: 330.0, occupancy: 'F', heightFromGround: 4.5 },
        { floorName: 'Second Floor (Offices)', builtUpArea: 380.0, carpetArea: 290.0, occupancy: 'F', heightFromGround: 8.1 },
      ],
      frontSetbackM: 5.5,
      rearSetbackM: 3.2,
      sideSetback1M: 2.2,
      sideSetback2M: 2.0,
      carParkingProvided: 16,
      twoWheelerParkingProvided: 45,
      disabledParkingProvided: 2,
      loadingBaysProvided: 1,
      parkingBayWidthM: 2.5,
      parkingBayLengthM: 5.0,
      drivewayWidthM: 5.0,
      openWellInPlot: false,
      distanceWellToSepticTankM: 0,
      distanceWellToSoakPitM: 0,
      distanceSepticTankToBoundaryM: 2.0,
      rwhTankCapacityLiters: 15000,
      solarPvCapacityKwp: 5.0,
      solidWasteUnitProvided: true,
      biogasPlantOrCompostProvided: true,
      mainStaircaseWidthM: 1.5,
      staircaseTreadCm: 30.0,
      staircaseRiserCm: 15.0,
      staircaseHeadroomM: 2.4,
      minHabitableRoomAreaSqM: 15.0,
      minHabitableRoomWidthM: 3.5,
      minHabitableRoomHeightM: 3.2,
      minKitchenAreaSqM: 6.0,
      minKitchenWidthM: 2.2,
      ventilationRatioPercent: 12.0,
      clearFirePassageWidthM: 4.5,
      hasLift: true,
      hasRampForDisabled: true,
      rampSlopeRatio: 12,
    },
    mockDrawings: [
      { id: 'c-1', category: 'location_plan', name: 'Location_Plan_1to1000.pdf', size: 1800000, status: 'verified', scale: '1:1000', sheetsCount: 1, extractedLabels: ['City Master Plan', 'KSRTC Road 12m'], uploadedAt: Date.now() - 3600000 },
      { id: 'c-2', category: 'site_plan', name: 'Site_Plan_Parking_Setbacks.dwg', size: 3800000, status: 'verified', scale: '1:200', sheetsCount: 1, extractedLabels: ['16 Cars', '45 Two-Wheelers', 'Loading Bay', 'Disabled Ramp'], uploadedAt: Date.now() - 3400000 },
      { id: 'c-3', category: 'floor_plans', name: 'Commercial_Floors_GF_FF_SF.pdf', size: 4500000, status: 'verified', scale: '1:100', sheetsCount: 3, extractedLabels: ['Retail Shops', 'Dual Fire Exits', 'Lift 8-Passenger'], uploadedAt: Date.now() - 3200000 },
      { id: 'c-4', category: 'elevation_plans', name: 'Front_Side_Elevations.pdf', size: 2800000, status: 'verified', scale: '1:100', sheetsCount: 1, extractedLabels: ['Height 11.5m', 'Signage Band'], uploadedAt: Date.now() - 3000000 },
      { id: 'c-5', category: 'section_plans', name: 'Longitudinal_and_Cross_Sections.pdf', size: 3200000, status: 'verified', scale: '1:100', sheetsCount: 1, extractedLabels: ['Clear Height 3.2m', 'Riser 15cm', 'Tread 30cm'], uploadedAt: Date.now() - 2800000 },
      { id: 'c-6', category: 'service_plans', name: 'STP_and_Drainage_Layout.pdf', size: 2100000, status: 'verified', scale: '1:100', sheetsCount: 1, extractedLabels: ['STP 10 KLD', 'Solid Waste Room'], uploadedAt: Date.now() - 2600000 },
      { id: 'c-7', category: 'parking_plans', name: 'Basement_and_Surface_Parking.pdf', size: 3400000, status: 'verified', scale: '1:200', sheetsCount: 1, extractedLabels: ['2.5x5.0m Slots', 'Driveway 5.0m', 'Entry/Exit 6.0m'], uploadedAt: Date.now() - 2400000 },
      { id: 'c-8', category: 'rwh_solar_plans', name: 'RWH_15KL_Solar_5kWp.pdf', size: 1900000, status: 'verified', scale: '1:100', sheetsCount: 1, extractedLabels: ['15KL Storage', '5kWp On-grid Solar'], uploadedAt: Date.now() - 2200000 },
    ],
  },
  {
    id: 'preset-small-plot',
    nameEn: 'Small Plot Residential House (<= 125 sq.m / 3 Cents - Rule 60/62 Exemption)',
    nameMl: 'ചെറിയ പ്ലോട്ടിലെ വീട് (125 ച.മീ / 3 സെന്റ് - ചട്ടം 60/62 ഇളവ്)',
    categoryEn: 'Special Small Plot Provisions',
    categoryMl: 'പ്രത്യേക ചെറിയ പ്ലോട്ട് ഇളവുകൾ',
    data: {
      projectName: 'Compact Urban Home',
      applicantName: 'Abdul Rahman & Fathima',
      architectEngineerName: 'Er. Shaji Varghese, Licensed Supervisor LSGD',
      licenseNumber: 'LSGD/SUP/B/2022/411',
      localBodyName: 'Aluva Municipality',
      wardNumber: 'Ward 14',
      surveyNumber: '89/4',
      villageName: 'Aluva West',
      talukName: 'Aluva',
      district: 'Ernakulam',
      jurisdiction: 'KMBR',
      occupancyGroup: 'A1',
      plotType: 'small_plot',
      plotAreaSqM: 115.0,
      plotAreaCents: 2.84,
      plotWidthM: 9.5,
      plotDepthM: 12.1,
      roadAccessWidthM: 2.4,
      buildingHeightM: 6.8,
      numberOfFloors: 2,
      groundCoverageSqM: 72.0,
      totalBuiltUpAreaSqM: 135.0,
      totalFloorAreaSqM: 122.0,
      totalCarpetAreaSqM: 104.0,
      floors: [
        { floorName: 'Ground Floor', builtUpArea: 72.0, carpetArea: 56.0, occupancy: 'A1', heightFromGround: 0.6 },
        { floorName: 'First Floor', builtUpArea: 63.0, carpetArea: 48.0, occupancy: 'A1', heightFromGround: 3.6 },
      ],
      frontSetbackM: 1.9,
      rearSetbackM: 1.1,
      sideSetback1M: 1.0,
      sideSetback2M: 0.65,
      carParkingProvided: 1,
      twoWheelerParkingProvided: 1,
      disabledParkingProvided: 0,
      loadingBaysProvided: 0,
      parkingBayWidthM: 2.5,
      parkingBayLengthM: 5.0,
      drivewayWidthM: 2.4,
      openWellInPlot: false,
      distanceWellToSepticTankM: 0,
      distanceWellToSoakPitM: 0,
      distanceSepticTankToBoundaryM: 1.2,
      rwhTankCapacityLiters: 3000,
      solarPvCapacityKwp: 1.0,
      solidWasteUnitProvided: true,
      biogasPlantOrCompostProvided: true,
      mainStaircaseWidthM: 0.9,
      staircaseTreadCm: 25.0,
      staircaseRiserCm: 17.5,
      staircaseHeadroomM: 2.2,
      minHabitableRoomAreaSqM: 10.0,
      minHabitableRoomWidthM: 2.8,
      minHabitableRoomHeightM: 2.8,
      minKitchenAreaSqM: 5.5,
      minKitchenWidthM: 2.0,
      ventilationRatioPercent: 12.5,
      clearFirePassageWidthM: 2.0,
      hasLift: false,
      hasRampForDisabled: false,
      rampSlopeRatio: 10,
    },
    mockDrawings: [
      { id: 'sp-1', category: 'location_plan', name: 'Location_Plan_Aluva.pdf', size: 1100000, status: 'verified', scale: '1:2000', sheetsCount: 1, extractedLabels: ['Small Plot Boundary'], uploadedAt: Date.now() - 3600000 },
      { id: 'sp-2', category: 'site_plan', name: 'Small_Plot_SitePlan.dwg', size: 2100000, status: 'verified', scale: '1:200', sheetsCount: 1, extractedLabels: ['Rule 60 Exemption', 'Front 1.9m', 'Rear 1.1m', 'Side 0.65m'], uploadedAt: Date.now() - 3400000 },
      { id: 'sp-3', category: 'floor_plans', name: 'Compact_Home_FloorPlans.pdf', size: 2300000, status: 'verified', scale: '1:100', sheetsCount: 2, extractedLabels: ['2 Bedrooms', 'Kitchen 5.5sqm'], uploadedAt: Date.now() - 3200000 },
      { id: 'sp-4', category: 'elevation_plans', name: 'Elevations_6.8m.pdf', size: 1600000, status: 'verified', scale: '1:100', sheetsCount: 1, extractedLabels: ['Height 6.8m'], uploadedAt: Date.now() - 3000000 },
      { id: 'sp-5', category: 'section_plans', name: 'CrossSection_Stair_Toilet.pdf', size: 1800000, status: 'verified', scale: '1:100', sheetsCount: 1, extractedLabels: ['Tread 25cm', 'Riser 17.5cm'], uploadedAt: Date.now() - 2800000 },
      { id: 'sp-6', category: 'service_plans', name: 'Septic_Tank_and_RWH_Plan.pdf', size: 1400000, status: 'verified', scale: '1:100', sheetsCount: 1, extractedLabels: ['3000L RWH', 'Septic Tank 1.2m from wall'], uploadedAt: Date.now() - 2600000 },
      { id: 'sp-7', category: 'rwh_solar_plans', name: 'RWH_Terrace_Layout.pdf', size: 1200000, status: 'verified', scale: '1:100', sheetsCount: 1, extractedLabels: ['Roof catchment 72sqm'], uploadedAt: Date.now() - 2400000 },
    ],
  },
];
